/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BoxPane: typeof import('./src/components/box-pane/box-pane.vue')['default']
    CommonHeader: typeof import('./src/components/common-header/common-header.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    InfoPane: typeof import('./src/components/info-pane/info-pane.vue')['default']
    InfoProgress: typeof import('./src/components/info-progress/info-progress.vue')['default']
    LeftPane: typeof import('./src/components/left-pane/left-pane.vue')['default']
    LinkGroup: typeof import('./src/components/link-group/link-group.vue')['default']
    LinkGrup: typeof import('./src/components/link-grup.vue')['default']
    ResourceInfo: typeof import('./src/components/resource-info/resource-info.vue')['default']
    RightPane: typeof import('./src/components/right-pane/right-pane.vue')['default']
    SafetyInfo: typeof import('./src/components/safety-info/safety-info.vue')['default']
    Time: typeof import('./src/components/time/index.vue')['default']
  }
}
